# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import monitoreo_pb2 as monitoreo__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in monitoreo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MonitoreoServiceStub(object):
    """Monitoreo y Cliente
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ActualizarCliente = channel.unary_unary(
                '/monitoreo.MonitoreoService/ActualizarCliente',
                request_serializer=monitoreo__pb2.EstadoReserva.SerializeToString,
                response_deserializer=monitoreo__pb2.ConfirmacionCliente.FromString,
                _registered_method=True)
        self.StreamActualizaciones = channel.stream_stream(
                '/monitoreo.MonitoreoService/StreamActualizaciones',
                request_serializer=monitoreo__pb2.EstadoReserva.SerializeToString,
                response_deserializer=monitoreo__pb2.ConfirmacionCliente.FromString,
                _registered_method=True)


class MonitoreoServiceServicer(object):
    """Monitoreo y Cliente
    """

    def ActualizarCliente(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamActualizaciones(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonitoreoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ActualizarCliente': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarCliente,
                    request_deserializer=monitoreo__pb2.EstadoReserva.FromString,
                    response_serializer=monitoreo__pb2.ConfirmacionCliente.SerializeToString,
            ),
            'StreamActualizaciones': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamActualizaciones,
                    request_deserializer=monitoreo__pb2.EstadoReserva.FromString,
                    response_serializer=monitoreo__pb2.ConfirmacionCliente.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'monitoreo.MonitoreoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('monitoreo.MonitoreoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MonitoreoService(object):
    """Monitoreo y Cliente
    """

    @staticmethod
    def ActualizarCliente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/monitoreo.MonitoreoService/ActualizarCliente',
            monitoreo__pb2.EstadoReserva.SerializeToString,
            monitoreo__pb2.ConfirmacionCliente.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamActualizaciones(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/monitoreo.MonitoreoService/StreamActualizaciones',
            monitoreo__pb2.EstadoReserva.SerializeToString,
            monitoreo__pb2.ConfirmacionCliente.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
