# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import reserva_pb2 as reserva__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in reserva_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReservaServiceStub(object):
    """Cliente-Reserva
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnviarSolicitud = channel.unary_unary(
                '/reserva.ReservaService/EnviarSolicitud',
                request_serializer=reserva__pb2.SolicitudReserva.SerializeToString,
                response_deserializer=reserva__pb2.ConfirmacionRecepcion.FromString,
                _registered_method=True)
        self.ProcesarReservas = channel.unary_unary(
                '/reserva.ReservaService/ProcesarReservas',
                request_serializer=reserva__pb2.ListaSolicitudes.SerializeToString,
                response_deserializer=reserva__pb2.ConfirmacionRecepcion.FromString,
                _registered_method=True)


class ReservaServiceServicer(object):
    """Cliente-Reserva
    """

    def EnviarSolicitud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcesarReservas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReservaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnviarSolicitud': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarSolicitud,
                    request_deserializer=reserva__pb2.SolicitudReserva.FromString,
                    response_serializer=reserva__pb2.ConfirmacionRecepcion.SerializeToString,
            ),
            'ProcesarReservas': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcesarReservas,
                    request_deserializer=reserva__pb2.ListaSolicitudes.FromString,
                    response_serializer=reserva__pb2.ConfirmacionRecepcion.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reserva.ReservaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('reserva.ReservaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReservaService(object):
    """Cliente-Reserva
    """

    @staticmethod
    def EnviarSolicitud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reserva.ReservaService/EnviarSolicitud',
            reserva__pb2.SolicitudReserva.SerializeToString,
            reserva__pb2.ConfirmacionRecepcion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcesarReservas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reserva.ReservaService/ProcesarReservas',
            reserva__pb2.ListaSolicitudes.SerializeToString,
            reserva__pb2.ConfirmacionRecepcion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RegistroServiceStub(object):
    """Reserva-Registro
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegistrarReserva = channel.unary_unary(
                '/reserva.RegistroService/RegistrarReserva',
                request_serializer=reserva__pb2.ReservaConfirmada.SerializeToString,
                response_deserializer=reserva__pb2.ConfirmacionRegistro.FromString,
                _registered_method=True)


class RegistroServiceServicer(object):
    """Reserva-Registro
    """

    def RegistrarReserva(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistroServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegistrarReserva': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarReserva,
                    request_deserializer=reserva__pb2.ReservaConfirmada.FromString,
                    response_serializer=reserva__pb2.ConfirmacionRegistro.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reserva.RegistroService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('reserva.RegistroService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RegistroService(object):
    """Reserva-Registro
    """

    @staticmethod
    def RegistrarReserva(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reserva.RegistroService/RegistrarReserva',
            reserva__pb2.ReservaConfirmada.SerializeToString,
            reserva__pb2.ConfirmacionRegistro.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
