# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: registro.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'registro.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eregistro.proto\x12\x08registro\"\x93\x01\n\x11ReservaConfirmada\x12\x16\n\x0ereservation_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\x12\x12\n\nparty_size\x18\x04 \x01(\x05\x12\x13\n\x0bpreferences\x18\x05 \x01(\t\x12\x10\n\x08table_id\x18\x06 \x01(\t\x12\x0e\n\x06status\x18\x07 \x01(\t\"8\n\x14\x43onfirmacionRegistro\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2b\n\x0fRegistroService\x12O\n\x10RegistrarReserva\x12\x1b.registro.ReservaConfirmada\x1a\x1e.registro.ConfirmacionRegistroB\x19Z\x17proto/registro;registrob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'registro_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\027proto/registro;registro'
  _globals['_RESERVACONFIRMADA']._serialized_start=29
  _globals['_RESERVACONFIRMADA']._serialized_end=176
  _globals['_CONFIRMACIONREGISTRO']._serialized_start=178
  _globals['_CONFIRMACIONREGISTRO']._serialized_end=234
  _globals['_REGISTROSERVICE']._serialized_start=236
  _globals['_REGISTROSERVICE']._serialized_end=334
# @@protoc_insertion_point(module_scope)
