# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reserva.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'reserva.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rreserva.proto\x12\x07reserva\"X\n\x10SolicitudReserva\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05phone\x18\x02 \x01(\t\x12\x12\n\nparty_size\x18\x03 \x01(\x05\x12\x13\n\x0bpreferences\x18\x04 \x01(\t\"B\n\x10ListaSolicitudes\x12.\n\x0bsolicitudes\x18\x01 \x03(\x0b\x32\x19.reserva.SolicitudReserva\"\x93\x01\n\x11ReservaConfirmada\x12\x16\n\x0ereservation_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\x12\x12\n\nparty_size\x18\x04 \x01(\x05\x12\x13\n\x0bpreferences\x18\x05 \x01(\t\x12\x10\n\x08table_id\x18\x06 \x01(\t\x12\x0e\n\x06status\x18\x07 \x01(\t\"9\n\x15\x43onfirmacionRecepcion\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"8\n\x14\x43onfirmacionRegistro\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xad\x01\n\x0eReservaService\x12L\n\x0f\x45nviarSolicitud\x12\x19.reserva.SolicitudReserva\x1a\x1e.reserva.ConfirmacionRecepcion\x12M\n\x10ProcesarReservas\x12\x19.reserva.ListaSolicitudes\x1a\x1e.reserva.ConfirmacionRecepcion2`\n\x0fRegistroService\x12M\n\x10RegistrarReserva\x12\x1a.reserva.ReservaConfirmada\x1a\x1d.reserva.ConfirmacionRegistroB\x11Z\x0f./proto;reservab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reserva_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017./proto;reserva'
  _globals['_SOLICITUDRESERVA']._serialized_start=26
  _globals['_SOLICITUDRESERVA']._serialized_end=114
  _globals['_LISTASOLICITUDES']._serialized_start=116
  _globals['_LISTASOLICITUDES']._serialized_end=182
  _globals['_RESERVACONFIRMADA']._serialized_start=185
  _globals['_RESERVACONFIRMADA']._serialized_end=332
  _globals['_CONFIRMACIONRECEPCION']._serialized_start=334
  _globals['_CONFIRMACIONRECEPCION']._serialized_end=391
  _globals['_CONFIRMACIONREGISTRO']._serialized_start=393
  _globals['_CONFIRMACIONREGISTRO']._serialized_end=449
  _globals['_RESERVASERVICE']._serialized_start=452
  _globals['_RESERVASERVICE']._serialized_end=625
  _globals['_REGISTROSERVICE']._serialized_start=627
  _globals['_REGISTROSERVICE']._serialized_end=723
# @@protoc_insertion_point(module_scope)
