// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/registro.proto

package registro

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReservaConfirmada struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	PartySize     int32                  `protobuf:"varint,4,opt,name=party_size,json=partySize,proto3" json:"party_size,omitempty"`
	Preferences   string                 `protobuf:"bytes,5,opt,name=preferences,proto3" json:"preferences,omitempty"`
	TableId       string                 `protobuf:"bytes,6,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservaConfirmada) Reset() {
	*x = ReservaConfirmada{}
	mi := &file_proto_registro_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservaConfirmada) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservaConfirmada) ProtoMessage() {}

func (x *ReservaConfirmada) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registro_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservaConfirmada.ProtoReflect.Descriptor instead.
func (*ReservaConfirmada) Descriptor() ([]byte, []int) {
	return file_proto_registro_proto_rawDescGZIP(), []int{0}
}

func (x *ReservaConfirmada) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReservaConfirmada) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReservaConfirmada) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ReservaConfirmada) GetPartySize() int32 {
	if x != nil {
		return x.PartySize
	}
	return 0
}

func (x *ReservaConfirmada) GetPreferences() string {
	if x != nil {
		return x.Preferences
	}
	return ""
}

func (x *ReservaConfirmada) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *ReservaConfirmada) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ConfirmacionRegistro struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmacionRegistro) Reset() {
	*x = ConfirmacionRegistro{}
	mi := &file_proto_registro_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmacionRegistro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmacionRegistro) ProtoMessage() {}

func (x *ConfirmacionRegistro) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registro_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmacionRegistro.ProtoReflect.Descriptor instead.
func (*ConfirmacionRegistro) Descriptor() ([]byte, []int) {
	return file_proto_registro_proto_rawDescGZIP(), []int{1}
}

func (x *ConfirmacionRegistro) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmacionRegistro) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_registro_proto protoreflect.FileDescriptor

const file_proto_registro_proto_rawDesc = "" +
	"\n" +
	"\x14proto/registro.proto\x12\bregistro\"\xd8\x01\n" +
	"\x11ReservaConfirmada\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"party_size\x18\x04 \x01(\x05R\tpartySize\x12 \n" +
	"\vpreferences\x18\x05 \x01(\tR\vpreferences\x12\x19\n" +
	"\btable_id\x18\x06 \x01(\tR\atableId\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"J\n" +
	"\x14ConfirmacionRegistro\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2b\n" +
	"\x0fRegistroService\x12O\n" +
	"\x10RegistrarReserva\x12\x1b.registro.ReservaConfirmada\x1a\x1e.registro.ConfirmacionRegistroB\x19Z\x17proto/registro;registrob\x06proto3"

var (
	file_proto_registro_proto_rawDescOnce sync.Once
	file_proto_registro_proto_rawDescData []byte
)

func file_proto_registro_proto_rawDescGZIP() []byte {
	file_proto_registro_proto_rawDescOnce.Do(func() {
		file_proto_registro_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_registro_proto_rawDesc), len(file_proto_registro_proto_rawDesc)))
	})
	return file_proto_registro_proto_rawDescData
}

var file_proto_registro_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_registro_proto_goTypes = []any{
	(*ReservaConfirmada)(nil),    // 0: registro.ReservaConfirmada
	(*ConfirmacionRegistro)(nil), // 1: registro.ConfirmacionRegistro
}
var file_proto_registro_proto_depIdxs = []int32{
	0, // 0: registro.RegistroService.RegistrarReserva:input_type -> registro.ReservaConfirmada
	1, // 1: registro.RegistroService.RegistrarReserva:output_type -> registro.ConfirmacionRegistro
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_registro_proto_init() }
func file_proto_registro_proto_init() {
	if File_proto_registro_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_registro_proto_rawDesc), len(file_proto_registro_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_registro_proto_goTypes,
		DependencyIndexes: file_proto_registro_proto_depIdxs,
		MessageInfos:      file_proto_registro_proto_msgTypes,
	}.Build()
	File_proto_registro_proto = out.File
	file_proto_registro_proto_goTypes = nil
	file_proto_registro_proto_depIdxs = nil
}
