// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/reserva.proto

package reserva

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SolicitudReserva struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	PartySize     int32                  `protobuf:"varint,3,opt,name=party_size,json=partySize,proto3" json:"party_size,omitempty"`
	Preferences   string                 `protobuf:"bytes,4,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolicitudReserva) Reset() {
	*x = SolicitudReserva{}
	mi := &file_proto_reserva_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudReserva) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudReserva) ProtoMessage() {}

func (x *SolicitudReserva) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reserva_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudReserva.ProtoReflect.Descriptor instead.
func (*SolicitudReserva) Descriptor() ([]byte, []int) {
	return file_proto_reserva_proto_rawDescGZIP(), []int{0}
}

func (x *SolicitudReserva) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SolicitudReserva) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SolicitudReserva) GetPartySize() int32 {
	if x != nil {
		return x.PartySize
	}
	return 0
}

func (x *SolicitudReserva) GetPreferences() string {
	if x != nil {
		return x.Preferences
	}
	return ""
}

type ListaSolicitudes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Solicitudes   []*SolicitudReserva    `protobuf:"bytes,1,rep,name=solicitudes,proto3" json:"solicitudes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaSolicitudes) Reset() {
	*x = ListaSolicitudes{}
	mi := &file_proto_reserva_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaSolicitudes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaSolicitudes) ProtoMessage() {}

func (x *ListaSolicitudes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reserva_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaSolicitudes.ProtoReflect.Descriptor instead.
func (*ListaSolicitudes) Descriptor() ([]byte, []int) {
	return file_proto_reserva_proto_rawDescGZIP(), []int{1}
}

func (x *ListaSolicitudes) GetSolicitudes() []*SolicitudReserva {
	if x != nil {
		return x.Solicitudes
	}
	return nil
}

type ConfirmacionRecepcion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmacionRecepcion) Reset() {
	*x = ConfirmacionRecepcion{}
	mi := &file_proto_reserva_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmacionRecepcion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmacionRecepcion) ProtoMessage() {}

func (x *ConfirmacionRecepcion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reserva_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmacionRecepcion.ProtoReflect.Descriptor instead.
func (*ConfirmacionRecepcion) Descriptor() ([]byte, []int) {
	return file_proto_reserva_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmacionRecepcion) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmacionRecepcion) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_reserva_proto protoreflect.FileDescriptor

const file_proto_reserva_proto_rawDesc = "" +
	"\n" +
	"\x13proto/reserva.proto\x12\areserva\"}\n" +
	"\x10SolicitudReserva\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"party_size\x18\x03 \x01(\x05R\tpartySize\x12 \n" +
	"\vpreferences\x18\x04 \x01(\tR\vpreferences\"O\n" +
	"\x10ListaSolicitudes\x12;\n" +
	"\vsolicitudes\x18\x01 \x03(\v2\x19.reserva.SolicitudReservaR\vsolicitudes\"K\n" +
	"\x15ConfirmacionRecepcion\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xad\x01\n" +
	"\x0eReservaService\x12L\n" +
	"\x0fEnviarSolicitud\x12\x19.reserva.SolicitudReserva\x1a\x1e.reserva.ConfirmacionRecepcion\x12M\n" +
	"\x10ProcesarReservas\x12\x19.reserva.ListaSolicitudes\x1a\x1e.reserva.ConfirmacionRecepcionB\x17Z\x15proto/reserva;reservab\x06proto3"

var (
	file_proto_reserva_proto_rawDescOnce sync.Once
	file_proto_reserva_proto_rawDescData []byte
)

func file_proto_reserva_proto_rawDescGZIP() []byte {
	file_proto_reserva_proto_rawDescOnce.Do(func() {
		file_proto_reserva_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_reserva_proto_rawDesc), len(file_proto_reserva_proto_rawDesc)))
	})
	return file_proto_reserva_proto_rawDescData
}

var file_proto_reserva_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_reserva_proto_goTypes = []any{
	(*SolicitudReserva)(nil),      // 0: reserva.SolicitudReserva
	(*ListaSolicitudes)(nil),      // 1: reserva.ListaSolicitudes
	(*ConfirmacionRecepcion)(nil), // 2: reserva.ConfirmacionRecepcion
}
var file_proto_reserva_proto_depIdxs = []int32{
	0, // 0: reserva.ListaSolicitudes.solicitudes:type_name -> reserva.SolicitudReserva
	0, // 1: reserva.ReservaService.EnviarSolicitud:input_type -> reserva.SolicitudReserva
	1, // 2: reserva.ReservaService.ProcesarReservas:input_type -> reserva.ListaSolicitudes
	2, // 3: reserva.ReservaService.EnviarSolicitud:output_type -> reserva.ConfirmacionRecepcion
	2, // 4: reserva.ReservaService.ProcesarReservas:output_type -> reserva.ConfirmacionRecepcion
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_reserva_proto_init() }
func file_proto_reserva_proto_init() {
	if File_proto_reserva_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_reserva_proto_rawDesc), len(file_proto_reserva_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_reserva_proto_goTypes,
		DependencyIndexes: file_proto_reserva_proto_depIdxs,
		MessageInfos:      file_proto_reserva_proto_msgTypes,
	}.Build()
	File_proto_reserva_proto = out.File
	file_proto_reserva_proto_goTypes = nil
	file_proto_reserva_proto_depIdxs = nil
}
