// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: monitoreo.proto

package monitoreo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EstadoReserva struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`   // "exitosa", "fallida"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` //Detalles específicos
	TableId       string                 `protobuf:"bytes,4,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	PartySize     int32                  `protobuf:"varint,5,opt,name=party_size,json=partySize,proto3" json:"party_size,omitempty"`
	Preferences   string                 `protobuf:"bytes,6,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstadoReserva) Reset() {
	*x = EstadoReserva{}
	mi := &file_monitoreo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstadoReserva) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoReserva) ProtoMessage() {}

func (x *EstadoReserva) ProtoReflect() protoreflect.Message {
	mi := &file_monitoreo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoReserva.ProtoReflect.Descriptor instead.
func (*EstadoReserva) Descriptor() ([]byte, []int) {
	return file_monitoreo_proto_rawDescGZIP(), []int{0}
}

func (x *EstadoReserva) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EstadoReserva) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EstadoReserva) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EstadoReserva) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *EstadoReserva) GetPartySize() int32 {
	if x != nil {
		return x.PartySize
	}
	return 0
}

func (x *EstadoReserva) GetPreferences() string {
	if x != nil {
		return x.Preferences
	}
	return ""
}

type ConfirmacionCliente struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmacionCliente) Reset() {
	*x = ConfirmacionCliente{}
	mi := &file_monitoreo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmacionCliente) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmacionCliente) ProtoMessage() {}

func (x *ConfirmacionCliente) ProtoReflect() protoreflect.Message {
	mi := &file_monitoreo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmacionCliente.ProtoReflect.Descriptor instead.
func (*ConfirmacionCliente) Descriptor() ([]byte, []int) {
	return file_monitoreo_proto_rawDescGZIP(), []int{1}
}

func (x *ConfirmacionCliente) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

var File_monitoreo_proto protoreflect.FileDescriptor

const file_monitoreo_proto_rawDesc = "" +
	"\n" +
	"\x0fmonitoreo.proto\x12\tmonitoreo\"\xb1\x01\n" +
	"\rEstadoReserva\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x19\n" +
	"\btable_id\x18\x04 \x01(\tR\atableId\x12\x1d\n" +
	"\n" +
	"party_size\x18\x05 \x01(\x05R\tpartySize\x12 \n" +
	"\vpreferences\x18\x06 \x01(\tR\vpreferences\"1\n" +
	"\x13ConfirmacionCliente\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived2\xb8\x01\n" +
	"\x10MonitoreoService\x12M\n" +
	"\x11ActualizarCliente\x12\x18.monitoreo.EstadoReserva\x1a\x1e.monitoreo.ConfirmacionCliente\x12U\n" +
	"\x15StreamActualizaciones\x12\x18.monitoreo.EstadoReserva\x1a\x1e.monitoreo.ConfirmacionCliente(\x010\x01B\x13Z\x11./proto;monitoreob\x06proto3"

var (
	file_monitoreo_proto_rawDescOnce sync.Once
	file_monitoreo_proto_rawDescData []byte
)

func file_monitoreo_proto_rawDescGZIP() []byte {
	file_monitoreo_proto_rawDescOnce.Do(func() {
		file_monitoreo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monitoreo_proto_rawDesc), len(file_monitoreo_proto_rawDesc)))
	})
	return file_monitoreo_proto_rawDescData
}

var file_monitoreo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_monitoreo_proto_goTypes = []any{
	(*EstadoReserva)(nil),       // 0: monitoreo.EstadoReserva
	(*ConfirmacionCliente)(nil), // 1: monitoreo.ConfirmacionCliente
}
var file_monitoreo_proto_depIdxs = []int32{
	0, // 0: monitoreo.MonitoreoService.ActualizarCliente:input_type -> monitoreo.EstadoReserva
	0, // 1: monitoreo.MonitoreoService.StreamActualizaciones:input_type -> monitoreo.EstadoReserva
	1, // 2: monitoreo.MonitoreoService.ActualizarCliente:output_type -> monitoreo.ConfirmacionCliente
	1, // 3: monitoreo.MonitoreoService.StreamActualizaciones:output_type -> monitoreo.ConfirmacionCliente
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_monitoreo_proto_init() }
func file_monitoreo_proto_init() {
	if File_monitoreo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monitoreo_proto_rawDesc), len(file_monitoreo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_monitoreo_proto_goTypes,
		DependencyIndexes: file_monitoreo_proto_depIdxs,
		MessageInfos:      file_monitoreo_proto_msgTypes,
	}.Build()
	File_monitoreo_proto = out.File
	file_monitoreo_proto_goTypes = nil
	file_monitoreo_proto_depIdxs = nil
}
